### ISSUE TITLE
Liste der Probleme & Entscheidungen anfertigen

### ISSUE THREAD

**Issue by goekhan-klc** [goekhan-klc/RoadMap#13]

**Comment by Leonhtz** [comment]
Siehe unter Vorgehen ganz unten oder auch schon in der Präsi.

Weitere folgen noch.

**Comment by goekhan-klc** [comment]
Entscheidungen: 
- Welches Thema? Politik, Migation, Verkehr, Fußball, Autos, Gesellschaftliche Themen, Diskutable Themen
- Welche Technologie? Power BI oder Eigenentwicklung (Flask,Grafana,Pandas, Plotlib etc)
- Welche Datenquelle? Statistikportal der Länder oder Statistisches Bundesamt? Datenqualität?
- Excel oder CSV? CSV Dateien hatten eingeschränkte transfomationsmöglichkeiten, Excel-Dateien aber sehr große Dateigrößen, daher CSV (Ausgangsformat) -> Excel (Konsolidieren & Transformieren)-> CSV (Größe & Rechenaufwand reduzieren)
- Datenbank oder Datei? Ausgangsformat waren CSV-Dateien, daher wäre es sinnlos gewesen, über eine million einträge in eine datenbank zu friemeln. natürlich wären datebankoperationen, z.b. in sql entspannter und kontrollierter gewesen, aber letzlich konnte man in excel auch ganz gut experimentieren


Probleme: 
- Bundesland, Regierungsbezirk, Kreis und Gemeinde rausfinden -> Lösung war die Gemeincecode-Datenbank
- Für jeden Unfall eine Stadt angeben -> Über den Kreis-Code #18

**Comment by Leonhtz** [comment]
Einzelne Probleme wurden den zugehörigen Abschnitten zugeordnet.

Probleme wurden ebenfalls eingepflegt; auch in die Präsi.
