### ISSUE TITLE
Meilensteinplanung

### ISSUE THREAD

**Issue by goekhan-klc** [goekhan-klc/RoadMap#14]

**Comment by goekhan-klc** [comment]
Folgende Meilensteine waren Teil des Projekts:

- Brainstorming über das Thema des Projekts
- Kick-Off und Debatte über gewählte Technologien und Entscheidung über verwendete Technologien
- Installation PowerBI, Erstellung Git-Repo, Erstellung Discord, Erstellung OneDrive-Ordner
- Fertige Struktur für den Aufbau des Power-BI Dashboards und mögliche Metriken
- Vollständige Datenkonsolidierung, Datentransformation & Datenbereinigung
- Implementierung des Dashboards
- Abschließen der Dokumentation
- Abschließen der Präsentation

**Comment by Leonhtz** [comment]
In Kurzcharakterisierung / Grobplanung eingefügt.

Erledigt.
