### ISSUE TITLE
Hierarchischer Aufbau und Filterdimensionen notieren

### ISSUE THREAD

**Issue by goekhan-klc** [goekhan-klc/RoadMap#19]
![Image](https://github.com/user-attachments/assets/19b47e52-6e18-4c50-b437-3d835ae3cb3b)

**Comment by goekhan-klc** [comment]
- Also der Aufbau hat sich über die Zeit sehr stark verändert
- dabei hatten wir zu anfangs alles auf einer übersichtsseite und später alles deutlich strukturierter (vor allem nach art des informationsgehalts)

- Welcome - Einstiegsbild mit verlinkungen und erläuterungen
- RoadMap - Die Kartenansicht und FIlteroptionen
- CitySearch - Die Suche für städte mit einigen Kennzahlen und darstellung
- DaytimeGraph - einige Metriken und grafen zum zeitpunkt des unfalls
- WeatherGraph - einige Metriken und grafen zum Wetter des Unfallzeitpunkts
- SafetyGraph - einige Metriken zu Fragen bezogen zur sicherheit von städten, unfallhäufigkeiten, folgen und ursachen von unfällen
- Chat - ggf. noch ein chat um mit den Daten zu interargieren (optional nach aufwand)

**Comment by goekhan-klc** [comment]
Filterdimensionen:

- Zeitlich (Jahre, Monate, Wochentage, Stunden)
- Geografisch (Koordinaten, Städte über den Kreiscode [Eigenentwicklung])
- Beteiligung (Wer war am unfall beteiligt)
- Art & Folge (Grund für den Unfall und Folge also verletzung oder tot)

**Comment by Leonhtz** [comment]
Ins Wiki  "Visualisierung und Implementierung des Dashboards" eingepflegt.
