### ISSUE TITLE
Anfertigung der Graph-Seiten

### ISSUE THREAD

**Issue by goekhan-klc** [goekhan-klc/RoadMap#3]

**Comment by LGhoull** [comment]
## Meine Idee bisher:
Man hat eine Liste von allen Orten/Gemeinden.
### Spalten
- Name
- Anzahl Unfälle
- Anteil an allen Unfällen
- Rangliste (Beispielwert: #2 -> Zweitmeiste Unfälle)
### Funktionen
- Filtern wie bei der map, am besten werden die filter von der map übernommen
- Suchen nach Name
